### ISSUE TITLE
Fundraising

### ISSUE THREAD

**Issue by jhilden** [opencodetown/Chaos-Communication-Camp-2015#11]
So from #7 we know that we will need at least 1215€ or 1855€ and that we have to place our tent order until June 20th.  So let's start thinking about how to get the funds together?

If I remember correctly the Ruby Berlin e.V. agreed to handle the money for this, is that correct?  @skade @thilo

I would the the first step would be to ask around in our companies if and how much they would be willing to chip in and to collect the information here.

I think it would also be nice to collect money from indiviuals.  How could we do that?  Could we just do bank transfers to the Ruby e.V.?  Or should/could we set up something on betterplace, kickstarter, etc.?

Anybody interested in coordinating the whole fundraising topic?

**Comment by Lelith** [comment]
i just wanted to drop in a question if we also should add other things to that budget. like food, drinks, garbage bags, cleaning things, paper plates, cups, tape etc.

or shall we calculate these "living" costs extra and everyone who joins the village will pay for these things?

**Comment by skade** [comment]
Ruby Berlin has a betterplace account, we can set up a fundraiser quickly. Bank Transfers are also possible. I'll send out a mail to Roman tonight.

@lelith I would try to do so. I'm not sure about food, but cleaning stuff should be planned for. Food would be a great way to get people into the tent, though and I love cooking \o/. Let's cut that budget off, though, we can also spontaneously provide in August.

**Comment by Lelith** [comment]
ok, will create a new issue for all kind of eating and drinking. to see what we need and how much budget we need for that.

**Comment by skade** [comment]
Who would be willing to set up a fundraiser if I hand out an account? (please post your email or send it to me at florian@rubyberlin.org)

**Comment by skade** [comment]
Okay, lets take a structured approach: we need a rough guess about our budget until the 15th of June. Tents + Chairs. We need to raise the budget until July 20th. We need to make sure Ruby Berlin finance can wire the funds to that date latest.

**Comment by skade** [comment]
I created a fundraiser on betterplace, which is waiting for review.

**Comment by finnp** [comment]
@skade perfekt :bee: :raised_hands:

**Comment by ralphtheninja** [comment]
I'd be willing to pitch in 200-300€ easily. Lets do this. It's going to be epic :)

**Comment by skade** [comment]
Crowdfunding is live here:

https://www.betterplace.org/de/projects/30076-an-assembly-on-chaos-communication-camp-providing-free-teaching

Feel free to tweet, not just retweet.

Donations are _tax deducible_.

**Comment by ralphtheninja** [comment]
Cool. I think we should try to tweet the english version of the page though, not everyone speaks german.

https://www.betterplace.org/en/projects/30076-an-assembly-on-chaos-communication-camp-providing-free-teaching

**Comment by ralphtheninja** [comment]
Donated 250

**Comment by skade** [comment]
\o/ Funded. I added a stretch goal for a larger tent.

**Comment by ralphtheninja** [comment]
Woot! Which size would the stretch goal fulfill? 10x12?

**Comment by finnp** [comment]
Yap, have a look here: https://github.com/opencodetown/Chaos-Communication-Camp-2015/issues/7

**Comment by bitboxer** [comment]
Did anyone here do advertisment for the stretch goal somewhere? Did not see it on the rug:b mailinglist or other places :( .

**Comment by skade** [comment]
Not yet, only on the rust subreddit.

**Comment by jhilden** [comment]
I will try to write an Email to the Railscamp Newsletter today.

**Comment by skade** [comment]
I haven't got an invoice yet. Anyone knows someone got one?

**Comment by skade** [comment]
So, the invoice amounts to 2236.20 without tax (2661.08 with). As we are getting the tax back, we are about 100 Euro short, that's manageable. (current crowdfunding amounts to 2175 Euro)

**Comment by ralphtheninja** [comment]
@skade So does that mean we will get the bigger tent after all?

**Comment by skade** [comment]
@ralphtheninja We ordered the bigger tent last month already :).

https://github.com/opencodetown/Chaos-Communication-Camp-2015/issues/7

**Comment by ralphtheninja** [comment]
Sweeeet! :beers:
