### ISSUE TITLE
Next Organizers Meeting (Berlin / Online)

### ISSUE THREAD

**Issue by finnp** [opencodetown/Chaos-Communication-Camp-2015#13]
**Update:** We meet at Asquera (Ohlauer Str. 43, 10999 Berlin, Germany) on Tuesday, June 16th at 7pm.

Hey,

I think we should have a meeting again :). We can do this somewhere in Berlin and people who are not in Berlin can use some kind of video chat to join.

Please use this doodle, so we can **decide on a date: http://doodle.com/bpzang8kamuuu4f9#table**

The sooner the better, since we have to register our village until June 20th

If we find a time slot, where @Argorak has time, we could do this at Asquera again.

Here is some things we need to do. Feel free to comment with additional action or discussion points.
### Attendees
- [x] Finn
- [x] Florian
- [x] Kathrin
- [x] Ben
### Agenda
- [x] Create Village page: [OpenCodeTown](http://events.ccc.de/camp/2015/wiki/Village:OpenCodeTown)
- [x] [Rent the Tent](https://events.ccc.de/camp/2015/wiki/Rent_a_Tent)
- [x] Move or rename the GitHub organisation

Best,
Finn

PS: If none of the dates work for you, suggest another date here, so I can add it to the doodle.

**Comment by finnp** [comment]
Hey @anoukruhaak @nerdbabe @lislis @johannhof @jhilden @cashewkernchen, can you fill out the doodle up there as well? Right now it looks like we will meet next Friday.

**Comment by anoukruhaak** [comment]
I won't be back in Berlin until Tuesday 16, but I could see if another Hackership organizer can come instead if you settle on Friday!

**Comment by finnp** [comment]
Okay everone, it looks like most people are able to join on **June 16th**

@skade Does it work out for you to do the meeting at Asquera again?

@lelith @jhilden @nerdbabe @anoukruhaak Mark your calendars with June 16th, 7pm :blush:

@lislis @Realtin Looks like you have no time on that day :confused:

**Comment by skade** [comment]
Tuesday fits, we can meet at my office.

**Comment by finnp** [comment]
Great!
![meeting](http://i.giphy.com/ZphsnOa1fNEQ.gif)

**Comment by Realtin** [comment]
![owls](http://i.imgur.com/35Qxgty.gif)
wish I could be there but I can't skip Rubicons all the time :/

**Comment by Lelith** [comment]
@skade can you give me the address to your office?

**Comment by skade** [comment]
Ohlauer Straße 43
10999 Berlin

Aufgang C, asquera GmbH/SIILI Solutions

Closest Bus stop is Ohlauer Straße (M29), closest subway is Schönleinstraße.

https://www.google.de/maps/place/Ohlauer+Str.+43,+10999+Berlin/@52.49403,13.4292,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84fb457ec5c5b:0xdea4d44c5a60186e?hl=de

My phone number is: +49 172 8122469

@Lelith Ping me on twitter before you arrive, the door bells are very high :(.

**Comment by Lelith** [comment]
:P ich lass einfach mal kurz anklingeln, dafür brauch ich kein twitter.

**Comment by finnp** [comment]
If anyone can not attend in person. I've created a talky hangout: https://beta.talky.io/by-a-crimson-surf . Not sure if this works, but worth a try.

**Comment by jhilden** [comment]
Sorry, but I'm on the go and unfortunately won't be able to join the meeting :(

But I will check read all potential updates later today and can take on smaller orga tasks.

**Comment by finnp** [comment]
Village Page is here: http://events.ccc.de/camp/2015/wiki/Village:OpenCodeTown
And we rented a tent as well :)

**Comment by ralphtheninja** [comment]
:+1:
