### ISSUE TITLE
Personal packlist

### ISSUE THREAD

**Issue by Lelith** [opencodetown/Chaos-Communication-Camp-2015#17]
hi here, i just wanted to share with you (especially the ones who did not go camping before) my general packlist i use for every festival or camping vacation i goto.

**Clothes**
Slippers (for the shower)
rain boots
jacket (hoody, jumper, sth warm)
rain coat
underwear (top, bottom, socks/ warm socks, tights)
sleeping clothes
sweater
tops (tees, longsleeve, dresses) 
bottoms (trousers long / short, skirts)

**Toiletry**
toothbrush &paste
shaving creme
razor
hairbrush / comb
hairspray
hair tie
contact-lenses & co
toilet paper
wet wipes & q-tips
shower
shampoo
big towel
small towel
washcloth
menstrual cup / menstrual hygenic articles
contraceptives (pill, condoms)
make up
Makeup remover
moisturizer
lip balm
nail file
mirror

**Camping**
tent
hammer
sleeping-bag
camping-mat
camping chair
extra tent pegs
gas cooker
mugs (fire-proof for boiling water)
plate
fork, spoon, knife
plastic canvas
lighter
can opener
pillow
lock
water can

**Misc**
Drinks (alcoholic / non alcoholic)
Food ( asia noodles, porridge, veggi sausages, soy pudding...)
book
play-cards (romme, munchkin...)
cash
handbag
anti-insect spray
sun-protection (cream, hat)
power cables (smartphone, music player)
camera (lomo, digital)
personal first aid (pain killers, plasters, insect gel, other medicin)
sewing supplies
gaffa
umbrella
disinfectant
sun glasses
flashlight
pocket knife
tissues

**Comment by ralphtheninja** [comment]
Thanks for sharing. I forgot about flashlight! :)
