### ISSUE TITLE
MaidSafe API Rust workshop

### ISSUE THREAD

**Issue by ioptio** [opencodetown/Chaos-Communication-Camp-2015#22]
Hi all - I work for a company MaidSafe who are building a set of GPLv3 libraries in Rust (https://crates.io/search?q=maidsafe) that are being used together for an open, censorship resistant, decentralised Internet (currently in testing phase). I will be at camp and would love to give an overview of what we're building and the API that developers (working in all languages) will be able to use to build decentralised applications.
Would this be of interest to folks?
The MaidSafe github has all of our code: https://github.com/maidsafe
I'm very open to tailoring the workshop to best support the sort of developers who'd be in attendance.

Let me know what you all think and if I can elaborate on anything. Thanks!

**Comment by finnp** [comment]
Hey @ioptio, I am not sure if this fits within our scope. @skade @Realtin @johannhof, what do you think?

**Comment by ioptio** [comment]
Thanks for the comment. Understood that this might not be in the direct scope of learning Rust. It would be more for folks who are looking for opportunities to supplement learning Rust with hands on project experience. Not sure if you were planning on doing any sort of lighting talk style presentations but maybe it would fit better as such? We have a bounty program starting up to offer Rust developers payment to build features and fix bugs in our core libraries which might be a good ending note for those who've been learning it all weekend and are looking for opportunities for more experience post-camp. http://blog.maidsafe.net/2015/07/08/maidsafe-code-bounty-program/

**Comment by skade** [comment]
@ioptio I'd be glad to meet you. I'm a bit in a rush currently, but I'm pretty sure we can work something out. Having an actual project to learn on is great for some people.

Is this the first time you attend a Chaos event?

**Comment by ralphtheninja** [comment]
I'd be interested :)

**Comment by skade** [comment]
@ioptio I just spoke to Johann today: we probably won't have a structured program except having certain hours for people to block off some space. It also doesn't quite fit the structure of the event to be too controlled (Chaos events are very - well - chaotic). Promotion also usually has to happen on site, Twitter isn't really helpful.

So just drop by, set a time and we try to promote it as much as possible.
