### ISSUE TITLE
Next organizer meeting

### ISSUE THREAD

**Issue by Lelith** [opencodetown/Chaos-Communication-Camp-2015#23]
as there are still a lot of open questions we should meet again! here is a doodle http://doodle.com/2yd96ziahu92bzif

**Comment by finnp** [comment]
@opencodetown/owners Please reply to the doodle :) We will probably meet in Berlin again, but if you are not around you can join via video chat.

**Comment by Lelith** [comment]
it looks like its difficult to find another appointment again. we also could create a organizer slack-chat or irc or something like that where we can communicate more directly than here.

**Comment by gnunicorn** [comment]
Or gitter: https://gitter.im/opencodetown/Chaos-Communication-Camp-2015 (if one of the project owners enables it.)

**Comment by finnp** [comment]
I just activated the gitter chat: https://gitter.im/opencodetown/Chaos-Communication-Camp-2015 I'm fine with using that.

**Comment by skade** [comment]
I have some time on the weekend. Anyone wants to meet for last questions?
