### ISSUE TITLE
Stuff we need to bring

### ISSUE THREAD

**Issue by Lelith** [opencodetown/Chaos-Communication-Camp-2015#27]
hi there, here is  a list of stuff we need to bring for setting up the tent environment. i would like to have a name to everything who would like to bring what and will take care of it.
- Beamer
- Canvas for beamer
- extension lead & power cables
- Lamps and general outdoor lighting, christmas lights, disco balls and any other shiny things are also welcome
- Paper Towels (kathrin)
- Cleaning Supplies (kathrin)
- single-use plates and cups (kathrin)
- network supplies e.g. ethernet cables, routers, switches
- gaffer tape
- flipchart
- clothes line
- clothes pins
- first aid kit
- paper & pens

**Comment by til** [comment]
I can bring this thing:

![img_20150811_231640](https://cloud.githubusercontent.com/assets/11211/9211260/38b9237e-4081-11e5-99c2-c4cf55fe5eea.jpg)

an LED "light snake", 10m, 15W, suited for outdoor use. I'll pack it unless someone says there is definitely already enough deco for the village. But can there ever be enough?

**Comment by finnp** [comment]
@til Yes bring it! I'll also bring  9m one.
