### ISSUE TITLE
Power - Distribution

### ISSUE THREAD

**Issue by ralphtheninja** [opencodetown/Chaos-Communication-Camp-2015#28]
There was a blog post about distributing power on the camp:

https://events.ccc.de/2015/07/21/power-distribution/

All distribution boxes can be found here:

https://events.ccc.de/camp/2015/wiki/Static:Power/DistributionBoxes

If you look at the [map](http://campmap.mazdermind.de/) the OpenCodeTown is in C3 (bottom left corner). The closest box to our tent is [this](https://events.ccc.de/camp/2015/wiki/Static:Power/DistributionBoxes#C3_.2832A_CEE.29)

I added OpenCodeTown to one of the sockets.

**Comment by finnp** [comment]
Nice, we probably will use all of those sockets though :)
