### ISSUE TITLE
Tent 

### ISSUE THREAD

**Issue by finnp** [opencodetown/Chaos-Communication-Camp-2015#7]
We decided that we want to [rent a tent and chairs/tables from CCC](https://events.ccc.de/camp/2015/wiki/Rent_a_Tent). There's no info yet how to expensive it will be this year. But judging from the 2011 prices one 54qm tent should be about 1.200 Euro. 

We'll have to wait for CCC to publish the prices, but we think having at least a 54qm tent would be nice.

It would be cool to have sponsors pay for it, but if it doesn't work out, let's do a betterplace campaign. 
### Prices

<table>
<tbody><tr>
<th> height (C) [m] </th>
<th> width (A) [m] </th>
<th> depth (B) [m] </th>
<th> A * B [m^2] </th>
<th> price [€]
</th></tr>
<tr>
<td> 2.3            </td>
<td> 3             </td>
<td> 6             </td>
<td> 18          </td>
<td> 658
</td></tr>
<tr>
<td> 2.3            </td>
<td> 6             </td>
<td> 6             </td>
<td> 36          </td>
<td> 982
</td></tr>
<tr>
<td> 2.3            </td>
<td> 6             </td>
<td> 9             </td>
<td> 54          </td>
<td> 1306
</td></tr>
<tr>
<td> 2.3            </td>
<td> 6             </td>
<td> 12            </td>
<td> 72          </td>
<td> 1630
</td></tr>
<tr>
<td> 2.3            </td>
<td> 8             </td>
<td> 9             </td>
<td> 72          </td>
<td> 1630
</td></tr>
</tr>
<tr>
<td> 2.3            </td>
<td> 10            </td>
<td> 9             </td>
<td> 90          </td>
<td> 1954 
</td></tr>
<tr>
<td> 2.3            </td>
<td> 8             </td>
<td> 12            </td>
<td> 96          </td>
<td> 2062 :circus_tent:
</td>
<tr>
<td> 2.3            </td>
<td> 10            </td>
<td> 12            </td>
<td> 120         </td>
<td> 2494
</td></tr>
<tr>
<td> 2.3            </td>
<td> 10            </td>
<td> 15            </td>
<td> 150         </td>
<td> 3034
</td></tr>
<tr>
<td> 2.3            </td>
<td> 10            </td>
<td> 18            </td>
<td> 180         </td>
<td> 3574
</td></tr>
<tr>
<td> 2.3            </td>
<td> 10            </td>
<td> 21            </td>
<td> 210         </td>
<td> 4114
</td></tr>
</tbody></table>

**Comment by Lelith** [comment]
hi there, there is a update on the tent page. 36m^2 cost about ~1200 euros. 
is there any sponsoring going on?

**Comment by skade** [comment]
Not yet. My company is usually available to chip in some smaller amount to close gaps.

**Comment by jhilden** [comment]
I think last time we probably had a tent of around 6x6 (= 36 too) and we were around 20 ppl.  If possible we should try to get something bigger.

Here are some impressions from last year, which also include some pics of the RubyVillage tent: https://www.flickr.com/photos/bumi/sets/72157627308226797

**Comment by Realtin** [comment]
I think they just posted relevant information! 

http://events.ccc.de/2015/06/03/village-rental-deadline/

**Comment by ralphtheninja** [comment]
There are many threads going on now :) I'll just reiterate what @skade mentioned before. The tent + ramp + tables and chairs have been funded. @skade added a stretch goal for a bigger tent.

See https://www.betterplace.org/en/projects/30076-an-assembly-on-chaos-communication-camp-providing-free-teaching if you want to pitch in

**Comment by finnp** [comment]
We now ordered the following:
- 8x12m (96m^2, 2062 Euro)
- 15 Tables
-  90 Chairs

**Comment by ralphtheninja** [comment]
:+1:
