### ISSUE TITLE
Naming the Village

### ISSUE THREAD

**Issue by finnp** [opencodetown/Chaos-Communication-Camp-2015#9]
Since there are people with different programming language and community backgrounds (Ruby, NodeSchool, Rust..), we would like have an inclusive village with a bit of a focus on learning languages (NodeSchool, RailsGirls, learning Rust..).

Florian came up with the working title `Polylodge` referencing that we are a polyglot community, but let's collect a few more ideas here :)

**Comment by jhilden** [comment]
The working title sounds like a good start to me.  We should also think about something like a tag line to explain our village a bit further.  Maybe something like "Learning programming languages for everybody - with Ruby, Rust, Node & friends"?

**Comment by finnp** [comment]
I would like to create an entry in the wiki, but I don't like `Polylodge`. It is not very descriptive. Also I guess most people think about `polygamy` not `polyglot`.

How about naming it  Open Code {Town, Village, Tent}  (inspired by opencode.club)?

**Comment by jhilden** [comment]
`Open Code` sounds just as good to me.  Definitely a :+1: (and +1 for creating a wiki entry)

What do you think about a subline in general and my concrete suggestion?

**Comment by finnp** [comment]
@jhilden Sounds great. I actually didn't remember that learning programming languages was out primary focus, but I am cool with that. Would replace Node with JavaScript though.

**Comment by jhilden** [comment]
Please tweak and improve it.  I wasn't there for the whole meeting, so maybe I got the focus a bit wrong.  I think it would be good if we had a second suggestion so people can express what they prefer/what they can best identifiy with.

**Comment by Realtin** [comment]
yes to poly getting mistaken for polygamy/amory. 

here are just some general ideas I had:
`helloworld.rb.rs.js` or  `#!/learn/to/code`

**Comment by skade** [comment]
`helloworld.{rb,rs,js}` maybe? Shell expansions for the win.

**Comment by Lelith** [comment]
i like #!learn/to/code

**Comment by skade** [comment]
Ich seh das Problem, dass das eine ganze Menge Zielgruppen zum Beispiel der Rust Berlin nicht anspricht (Profis, die die Sprache wechseln wollen).

**Comment by Lelith** [comment]
ich bin halt nicht sicher ob es wichtig ist das im namen ausgesagt wird was wir machen... dafür schreibt man dann ja einfach welche workshops man anbieten möchte.
ich fänd auch die idee mit OpenCode Town gut. nur Polylodge würde ich, aus bereits genannten gründen, nicht nehmen.

**Comment by finnp** [comment]
I think @Realtin ideas are pretty cool, but I think it might be better to have something that is pronouncable :) So maybe let's go with OCT? —  Oh, is it too early for the acronym? I meant Open Code Town.

**Comment by Lelith** [comment]
so 3 votes for Open Code Town

**Comment by Lelith** [comment]
is anyone strongly _against_ Open Code Town? if not i would choose this name, so we can add our village to the wiki

**Comment by skade** [comment]
I'm fine with OCT. It's a fitting umbrella name that doesn't shine over the other ones :+1:.

**Comment by jhilden** [comment]
+1 for Open Code Town

**Comment by finnp** [comment]
I created an org called https://github.com/opencodetown. I could invite everyone there and then move this repo there. The org name right now is a bit confusing

**Comment by skade** [comment]
@finnp I'm fine with that.

**Comment by ralphtheninja** [comment]
@finnp We should consider adding the village to https://events.ccc.de/camp/2015/wiki/Static:Villages and put a link to this github org

**Comment by finnp** [comment]
@ralphtheninja Yeah, we want to to this together on Tuesday. Registering your village there also informs the organizers about details like how big your tent is and how many people we expect.

**Comment by finnp** [comment]
I'll close this issue, because we decided to go with the name now.

**Comment by ralphtheninja** [comment]
@finnp Cool :+1:
